const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Kenya,Nairobi."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Kenya/Nairobi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "254745431734" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "254745431734";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "254745431734";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "Changs" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "changawa",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_08_31_05_18_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTIwLFxuICAgICAgICA1MSxcbiAgICAgICAgMyxcbiAgICAgICAgMjAzLFxuICAgICAgICAxODUsXG4gICAgICAgIDE5LFxuICAgICAgICA2OCxcbiAgICAgICAgNzYsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMTkzLFxuICAgICAgICAyMCxcbiAgICAgICAgMzgsXG4gICAgICAgIDg5LFxuICAgICAgICAxODYsXG4gICAgICAgIDY2LFxuICAgICAgICAxMDUsXG4gICAgICAgIDk5LFxuICAgICAgICAxMjMsXG4gICAgICAgIDIyNixcbiAgICAgICAgMTk3LFxuICAgICAgICAxOTAsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMjI0LFxuICAgICAgICAyMjcsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMjE5LFxuICAgICAgICAyMDUsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMjM4LFxuICAgICAgICAxMTYsXG4gICAgICAgIDIwOCxcbiAgICAgICAgNzBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgOTUsXG4gICAgICAgIDYxLFxuICAgICAgICAxMzAsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMjM4LFxuICAgICAgICA5MCxcbiAgICAgICAgMTQsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMTE2LFxuICAgICAgICAxMjIsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMTc2LFxuICAgICAgICAxMjMsXG4gICAgICAgIDI1LFxuICAgICAgICAxMDcsXG4gICAgICAgIDE5NCxcbiAgICAgICAgOCxcbiAgICAgICAgMTIzLFxuICAgICAgICAxNDAsXG4gICAgICAgIDQ0LFxuICAgICAgICAxOTgsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTUxLFxuICAgICAgICAxOTUsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjE0LFxuICAgICAgICAxMTgsXG4gICAgICAgIDgzLFxuICAgICAgICAxNTQsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTYwLFxuICAgICAgICA4NVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTkyLFxuICAgICAgICA0NyxcbiAgICAgICAgMjIsXG4gICAgICAgIDE0NixcbiAgICAgICAgNDIsXG4gICAgICAgIDgyLFxuICAgICAgICAyMzgsXG4gICAgICAgIDIyNSxcbiAgICAgICAgMTUzLFxuICAgICAgICA0LFxuICAgICAgICA3LFxuICAgICAgICA5MCxcbiAgICAgICAgMjEwLFxuICAgICAgICA0NCxcbiAgICAgICAgMTI2LFxuICAgICAgICAxMDYsXG4gICAgICAgIDE4OSxcbiAgICAgICAgNDksXG4gICAgICAgIDExLFxuICAgICAgICAxMDQsXG4gICAgICAgIDE0LFxuICAgICAgICAxNTgsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMjAxLFxuICAgICAgICAxNDMsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMixcbiAgICAgICAgMTIzLFxuICAgICAgICAxODIsXG4gICAgICAgIDMxLFxuICAgICAgICAxNzIsXG4gICAgICAgIDEwNVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMjQsXG4gICAgICAgIDIwNyxcbiAgICAgICAgMjExLFxuICAgICAgICAyNDMsXG4gICAgICAgIDYsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMTgzLFxuICAgICAgICAxNTcsXG4gICAgICAgIDI0NixcbiAgICAgICAgMjEzLFxuICAgICAgICAyMDcsXG4gICAgICAgIDI3LFxuICAgICAgICA0NSxcbiAgICAgICAgMTc3LFxuICAgICAgICAyMjksXG4gICAgICAgIDkwLFxuICAgICAgICAyMTUsXG4gICAgICAgIDMyLFxuICAgICAgICA5LFxuICAgICAgICAxMjQsXG4gICAgICAgIDEyNixcbiAgICAgICAgMTY0LFxuICAgICAgICAxNjcsXG4gICAgICAgIDEzLFxuICAgICAgICAxMDMsXG4gICAgICAgIDE4MixcbiAgICAgICAgMSxcbiAgICAgICAgNDMsXG4gICAgICAgIDM3LFxuICAgICAgICAyMzUsXG4gICAgICAgIDE5NyxcbiAgICAgICAgNVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTEyLFxuICAgICAgICAxODUsXG4gICAgICAgIDg0LFxuICAgICAgICAyMDUsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMTcsXG4gICAgICAgIDE5MixcbiAgICAgICAgMjE5LFxuICAgICAgICAxNzYsXG4gICAgICAgIDUwLFxuICAgICAgICAxNTYsXG4gICAgICAgIDEyMCxcbiAgICAgICAgNDQsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMjQ5LFxuICAgICAgICAyNTAsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMTY3LFxuICAgICAgICAxNixcbiAgICAgICAgOTUsXG4gICAgICAgIDI1NSxcbiAgICAgICAgMjIyLFxuICAgICAgICA3OCxcbiAgICAgICAgMzksXG4gICAgICAgIDIzMyxcbiAgICAgICAgNzMsXG4gICAgICAgIDgxLFxuICAgICAgICA2MSxcbiAgICAgICAgMjI1LFxuICAgICAgICAxMzYsXG4gICAgICAgIDEyMCxcbiAgICAgICAgOTVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgOTgsXG4gICAgICAgIDk3LFxuICAgICAgICA5OCxcbiAgICAgICAgMTQ3LFxuICAgICAgICAxMjYsXG4gICAgICAgIDg0LFxuICAgICAgICAxMDEsXG4gICAgICAgIDcsXG4gICAgICAgIDIzOCxcbiAgICAgICAgMTgyLFxuICAgICAgICAyNTUsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMixcbiAgICAgICAgMTI4LFxuICAgICAgICA5MSxcbiAgICAgICAgMzcsXG4gICAgICAgIDIsXG4gICAgICAgIDcyLFxuICAgICAgICAxMSxcbiAgICAgICAgNzksXG4gICAgICAgIDE0NixcbiAgICAgICAgMjUsXG4gICAgICAgIDExMSxcbiAgICAgICAgMTcyLFxuICAgICAgICAzMSxcbiAgICAgICAgMTkzLFxuICAgICAgICA0LFxuICAgICAgICA2LFxuICAgICAgICAxMDUsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMjAsXG4gICAgICAgIDUxXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDEwNCxcbiAgICAgICAgICAyMDYsXG4gICAgICAgICAgMjI3LFxuICAgICAgICAgIDE1MCxcbiAgICAgICAgICAxNzMsXG4gICAgICAgICAgMTg5LFxuICAgICAgICAgIDYwLFxuICAgICAgICAgIDU1LFxuICAgICAgICAgIDIwMixcbiAgICAgICAgICA3LFxuICAgICAgICAgIDIwNSxcbiAgICAgICAgICA4MSxcbiAgICAgICAgICAxOTUsXG4gICAgICAgICAgMTEwLFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDkwLFxuICAgICAgICAgIDI5LFxuICAgICAgICAgIDMsXG4gICAgICAgICAgMTMyLFxuICAgICAgICAgIDkxLFxuICAgICAgICAgIDM2LFxuICAgICAgICAgIDg5LFxuICAgICAgICAgIDUyLFxuICAgICAgICAgIDg0LFxuICAgICAgICAgIDk4LFxuICAgICAgICAgIDIyNSxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgOTQsXG4gICAgICAgICAgMzEsXG4gICAgICAgICAgMSxcbiAgICAgICAgICAyMzAsXG4gICAgICAgICAgMTIyXG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDEzOSxcbiAgICAgICAgICAyMjYsXG4gICAgICAgICAgMTUzLFxuICAgICAgICAgIDIzNSxcbiAgICAgICAgICAxNjIsXG4gICAgICAgICAgOTUsXG4gICAgICAgICAgMTgyLFxuICAgICAgICAgIDE5LFxuICAgICAgICAgIDI1LFxuICAgICAgICAgIDc3LFxuICAgICAgICAgIDE0NixcbiAgICAgICAgICAxNjYsXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgMTQ4LFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDk0LFxuICAgICAgICAgIDE0LFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICAyMDksXG4gICAgICAgICAgMTA5LFxuICAgICAgICAgIDExNyxcbiAgICAgICAgICAxODEsXG4gICAgICAgICAgMjMxLFxuICAgICAgICAgIDIyNixcbiAgICAgICAgICAyNDEsXG4gICAgICAgICAgNzcsXG4gICAgICAgICAgMTMyLFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICAxMzksXG4gICAgICAgICAgMjE5LFxuICAgICAgICAgIDIsXG4gICAgICAgICAgNzJcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNDcsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTIwLFxuICAgICAgICAxMSxcbiAgICAgICAgMTgwLFxuICAgICAgICAxMzYsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMjAxLFxuICAgICAgICAxNDcsXG4gICAgICAgIDE4MixcbiAgICAgICAgMTczLFxuICAgICAgICAyMixcbiAgICAgICAgMTcsXG4gICAgICAgIDc1LFxuICAgICAgICAzNCxcbiAgICAgICAgMjIsXG4gICAgICAgIDEyNCxcbiAgICAgICAgOSxcbiAgICAgICAgMTI0LFxuICAgICAgICA0NSxcbiAgICAgICAgMjQ2LFxuICAgICAgICAyNDAsXG4gICAgICAgIDgzLFxuICAgICAgICA2OSxcbiAgICAgICAgMTQ1LFxuICAgICAgICA2MixcbiAgICAgICAgMTY4LFxuICAgICAgICAxODcsXG4gICAgICAgIDE1NixcbiAgICAgICAgNjcsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMTk2LFxuICAgICAgICAxNDgsXG4gICAgICAgIDU5LFxuICAgICAgICAxMDIsXG4gICAgICAgIDY4LFxuICAgICAgICAxNDgsXG4gICAgICAgIDEyNyxcbiAgICAgICAgMjI1LFxuICAgICAgICAxMDMsXG4gICAgICAgIDExLFxuICAgICAgICAxNzgsXG4gICAgICAgIDI1NCxcbiAgICAgICAgOTksXG4gICAgICAgIDE3NixcbiAgICAgICAgNDYsXG4gICAgICAgIDQ3LFxuICAgICAgICAyMDAsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMTc1LFxuICAgICAgICAyMTAsXG4gICAgICAgIDUzLFxuICAgICAgICA2NixcbiAgICAgICAgMjM5LFxuICAgICAgICAyMzQsXG4gICAgICAgIDU4LFxuICAgICAgICAxMTksXG4gICAgICAgIDIzNyxcbiAgICAgICAgOCxcbiAgICAgICAgMjQ4LFxuICAgICAgICAxMDQsXG4gICAgICAgIDAsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTMzXG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiA2OSxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCI5cjlFbUdKSFFXNDJnQnZ4b3ExbzFMSi9UdHMzV0tibnZ1aFI3Vkw0K1p3PVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJyYU5TTnBzVFNLYS1KQzg3QS1vbmVRXCIsXG4gIFwicGhvbmVJZFwiOiBcImRmZWU0ODc5LWY2NzktNDQ0ZS04MDgzLTgxMjdkNTU3YTE3MlwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyMDgsXG4gICAgICAxNyxcbiAgICAgIDE5NixcbiAgICAgIDE0MyxcbiAgICAgIDE1LFxuICAgICAgMjAyLFxuICAgICAgNjEsXG4gICAgICAxNDEsXG4gICAgICA2MCxcbiAgICAgIDEwMCxcbiAgICAgIDQ2LFxuICAgICAgODcsXG4gICAgICAyMTQsXG4gICAgICAzOCxcbiAgICAgIDI0OSxcbiAgICAgIDE2NixcbiAgICAgIDE3MSxcbiAgICAgIDI1LFxuICAgICAgODYsXG4gICAgICAxNjNcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiBmYWxzZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE2MCxcbiAgICAgIDIzMyxcbiAgICAgIDIyMSxcbiAgICAgIDI0OSxcbiAgICAgIDEyMixcbiAgICAgIDg1LFxuICAgICAgMTUyLFxuICAgICAgMTg5LFxuICAgICAgOCxcbiAgICAgIDE1MyxcbiAgICAgIDgxLFxuICAgICAgMTMxLFxuICAgICAgMjYsXG4gICAgICAxNyxcbiAgICAgIDIwNyxcbiAgICAgIDEzNyxcbiAgICAgIDE2MCxcbiAgICAgIDIzNSxcbiAgICAgIDIxNixcbiAgICAgIDY1XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDSUxjOHF3RUVOeTFwc0VHR0FFZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJiNGJicW1IM1A3czNnV2Jqa1R0M1RISXVZNFBBcWxqL0VVam5ZdjVMM1ZVPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcImtWakNtSkx5NjVyZWp0N2d0b3Z6M3owM0I3VncraGhNUHJnQlJUNllhSEFSWXg1RFZETXFPRTh3YTIwcGlKTmVLRWFhM3o0amlOWXVsNU9zV3YrZkNRPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcImFpcG4xWFNTMXY0NlhVdVpCNkxoNjBJRkh6UnJzR1dTUlBScGRSZDVHemtRMWZXTHhxRVpOYWtuMTl5UE13dmg1cUF3ZkN0MERGNGVnZW84VVlEb2hnPT1cIlxuICB9LFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjU0NzQ1NDMxNzM0OjE5QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIxMzI3OTIyMTgzMjUxMzI6MTlAbGlkXCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyNTQ3NDU0MzE3MzQ6MTlAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxMTEsXG4gICAgICAgICAgMTM0LFxuICAgICAgICAgIDIxOSxcbiAgICAgICAgICAxNzAsXG4gICAgICAgICAgOTcsXG4gICAgICAgICAgMjQ3LFxuICAgICAgICAgIDYzLFxuICAgICAgICAgIDE4NyxcbiAgICAgICAgICA1NSxcbiAgICAgICAgICAxMjksXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDIyNyxcbiAgICAgICAgICAxNDUsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDc2LFxuICAgICAgICAgIDExNCxcbiAgICAgICAgICA0NixcbiAgICAgICAgICA5OSxcbiAgICAgICAgICAxMzEsXG4gICAgICAgICAgMTkyLFxuICAgICAgICAgIDE3MCxcbiAgICAgICAgICA4OCxcbiAgICAgICAgICAyNTUsXG4gICAgICAgICAgMTcsXG4gICAgICAgICAgNzIsXG4gICAgICAgICAgMjMxLFxuICAgICAgICAgIDk4LFxuICAgICAgICAgIDI1NCxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgODVcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcImFuZHJvaWRcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTc0NzU1NzA5MSxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQUx4a1wiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTHhqLmpzb24iOiAie1wia2V5RGF0YVwiOlwiREVMZkZnNjdoZnRjMFBwbFkya254M0cwR0pWaWxwSnliWk4wWlJWNUNIUT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMTY3ODk2MDY1LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFMeGsuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJZUFoxUFR6NWtrMGgyOGxrVmEyNTkwNVVmaytDTjI1VG9WS3AyTGtzb0dFPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjExNjc4OTYwNjUsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswXX0sXCJ0aW1lc3RhbXBcIjpcIjE3NDc1NTcwNjA2OTVcIn0iCn0=",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
